dist: focal
arch: amd64
os: linux
language: cpp

addons:
  apt:
    packages:
      - g++-8
      - cmake

script:
  - cmake -D ENABLE_COVERAGE=ON .
  - cmake --build . -- -j2
  - ctest -j2
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master