image:
  - Visual Studio 2017

clone_folder: c:\projects\source

branches:
  # whitelist
  only:
    - master

build_script:
- cmd: mkdir build
- cmd: cd build
- cmd: cmake c:\projects\source -G "Visual Studio 15"
- cmd: cmake --build . --config "Debug"
- cmd: ctest -C Debug